version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the root directory
    directory: "/"
    # Check for updates every day (you can change this to weekly, etc.)
    schedule:
      interval: "daily"
    # Optionally, assign reviewers to Dependabot PRs
    # reviewers:
    #   - "your-github-username"
    # Optionally, assign labels to Dependabot PRs
    # labels:
    #   - "dependencies"
    # Group updates for certain packages if desired (e.g., Prisma)
    # groups:
    #   prisma:
    #     patterns:
    #       - "@prisma/*"
    #       - "prisma"
    # Limit the number of open PRs for version updates
    open-pull-requests-limit: 10 